### ISSUE TITLE
A question about tensorflow_embedding config 

### ISSUE THREAD

**Issue by GaoQ1** [Aguila-team/Chinese_NLU_by_using_RASA_NLU#1]
有个疑问，在你采用tensorflow_embedding的那套pipeline中仍然使用了mitie的模型。你这里使用mitie目的是做slot filling的吧，其实我认为可以直接采用

language: "zh"

pipeline:
- name: "tokenizer_jieba"
- name: "ner_crf"
- name: "intent_featurizer_count_vectors"
  token_pattern: '(?u)\b\w+\b'
- name: "intent_classifier_tensorflow_embedding"

这样一套pipeline。当然我知道tensorflow_embedding和mitie, spacy那套相比在intent classify上存在OOV的问题，但是只要sotry足够多应该会有好的表现吧。

**Comment by howl-anderson** [comment]
非常感谢你的建议！我后面安排时间做一个你建议的 Pipeline 的评估，后续有结果我再通知你。
