### ISSUE TITLE
训练异常

### ISSUE THREAD

**Issue by AndersonYangOh** [Aguila-team/Chinese_NLU_by_using_RASA_NLU#2]
你好，我将dialogflow的agent导出到data下，训练时报No training examples found for dialogflow file，是dialogflow导出的数据还需要再处理吗？/data/下的目录结构应该是怎样的？

**Comment by howl-anderson** [comment]
数据文件位于：dataset/dialogflow/weather/Weather
详细文档见 https://github.com/Aguila-team/Chinese_NLU_by_using_RASA_NLU/blob/master/workflow.md

**Comment by AndersonYangOh** [comment]
> 数据文件位于：dataset/dialogflow/weather/Weather
> 详细文档见 https://github.com/Aguila-team/Chinese_NLU_by_using_RASA_NLU/blob/master/workflow.md

多谢  是没有使用脚本 convert_dataset_format.py导致
